name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Config Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go get -v -t -d ./...

      - name: Run Tests
        run: go test -v ./... -coverpkg=./... -coverprofile=coverage.cov ./...
